export const queryKeys = {
  documents: ['documents'] as const,
  document: (id: number) => ['documents', id] as const,
  stats: ['stats'] as const,
  sources: ['sources'] as const,
  tags: ['tags'] as const,
  search: ['search'] as const,
  settings: ['settings'] as const,
  backups: ['backups'] as const,
  automations: ['automations'] as const,
  audit: ['audit'] as const,
  documentHistory: (id: number) => ['documents', id, 'history'] as const,
  system: ['system'] as const,
  ocrHealth: ['ocr', 'health'] as const,
  aiHealth: ['ai', 'health'] as const,
  aiUsage: ['ai', 'usage'] as const,
  apiKey: (provider: string) => ['ai', 'apiKey', provider] as const,
  users: ['users'] as const,
}
